#!/bin/sh
HERE="$(dirname "$(readlink -f "$0")")"
APPDIR="$HERE"
if [ -n "$APPIMAGE" ]; then
    APPDIR_REAL="$(dirname "$APPIMAGE")"
    APPNAME="$(basename "$APPIMAGE")"
    export HOME="$APPDIR_REAL/${APPNAME}.home"
else
    export HOME="$HERE/../Celluloid.AppImage.home"
fi
mkdir -p \
    "$HOME/.config/celluloid/script-opts" \
    "$HOME/.cache" \
    "$HOME/.local/share"
export APPDIR="$HERE"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DATA_DIRS="$APPDIR/usr/share:/usr/local/share:/usr/share"
export GSETTINGS_SCHEMA_DIR="$APPDIR/usr/share/glib-2.0/schemas"
exec "$APPDIR/usr/bin/celluloid" \
    --mpv-hwdec=
